"""Generate /etc/fstab for the installed system."""

from __future__ import annotations

from distrostrap.core.context import InstallContext
from distrostrap.core.executor import Executor


def generate_fstab(ctx: InstallContext, executor: Executor) -> None:
    """Build and write ``/etc/fstab`` from context UUIDs and boot mode."""
    lines: list[str] = [
        "# /etc/fstab - generated by distrostrap",
        "# <file system>  <mount point>  <type>  <options>  <dump>  <pass>",
    ]

    if ctx.root_uuid:
        lines.append(f"UUID={ctx.root_uuid}  /  ext4  defaults  0  1")

    if ctx.boot_mode == "uefi" and ctx.esp_uuid:
        lines.append(f"UUID={ctx.esp_uuid}  /boot/efi  vfat  defaults  0  2")

    if ctx.swap_uuid:
        lines.append(f"UUID={ctx.swap_uuid}  none  swap  sw  0  0")

    lines.append("")  # trailing newline

    fstab_path = ctx.target_mount / "etc" / "fstab"
    fstab_path.parent.mkdir(parents=True, exist_ok=True)
    fstab_path.write_text("\n".join(lines))
